EXP_NAME="rSoccer-paper-val"
EXP_ARGS=""
case $1 in
0) python validate.py  -p 0 -n sa-0;;
1) python validate.py  -p 0 -n rsa-0;;
2) python validate.py  -p 0 -n il-ddpg-0;;
3) python validate.py  -p 0 -n il-maddpg-0;;
4) python validate.py  -p 0 -n jal-0;;
5) python validate.py  -p 0 -n sa-1;;
6) python validate.py  -p 0 -n rsa-1;;
7) python validate.py  -p 0 -n il-ddpg-1;;
8) python validate.py  -p 0 -n il-maddpg-1;;
9) python validate.py  -p 0 -n jal-1;;
10) python validate.py -p 0 -n sa-2;;
11) python validate.py -p 0 -n rsa-2;;
12) python validate.py -p 0 -n il-ddpg-2;;
13) python validate.py -p 0 -n il-maddpg-2;;
14) python validate.py -p 0 -n jal-2;;
15) python validate.py -p 1 -n sa-0;;
16) python validate.py -p 1 -n rsa-0;;
17) python validate.py -p 1 -n il-ddpg-0;;
18) python validate.py -p 1 -n il-maddpg-0;;
19) python validate.py -p 1 -n jal-0;;
20) python validate.py -p 1 -n sa-1;;
21) python validate.py -p 1 -n rsa-1;;
22) python validate.py -p 1 -n il-ddpg-1;;
23) python validate.py -p 1 -n il-maddpg-1;;
24) python validate.py -p 1 -n jal-1;;
25) python validate.py -p 1 -n sa-2;;
26) python validate.py -p 1 -n rsa-2;;
27) python validate.py -p 1 -n il-ddpg-2;;
28) python validate.py -p 1 -n il-maddpg-2;;
29) python validate.py -p 1 -n jal-2;;
30) python validate.py -p 2 -n sa-0;;
31) python validate.py -p 2 -n rsa-0;;
32) python validate.py -p 2 -n il-ddpg-0;;
33) python validate.py -p 2 -n il-maddpg-0;;
34) python validate.py -p 2 -n jal-0;;
35) python validate.py -p 2 -n sa-1;;
36) python validate.py -p 2 -n rsa-1;;
37) python validate.py -p 2 -n il-ddpg-1;;
38) python validate.py -p 2 -n il-maddpg-1;;
39) python validate.py -p 2 -n jal-1;;
40) python validate.py -p 2 -n sa-2;;
41) python validate.py -p 2 -n rsa-2;;
42) python validate.py -p 2 -n il-ddpg-2;;
43) python validate.py -p 2 -n il-maddpg-2;;
44) python validate.py -p 2 -n jal-2;;
*) echo "Opcao Invalida!" ;;
esac